import React from "react";
import IngressantesTemplate from "../concepts/ingressantes/componentes/templates/IngressantesTemplate";
import Head from "next/head";

const Ingressantes: React.FC = () => {
  return (
    <>
      <Head>
        <title>Desafio Muralis - Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/arvore.png" />
      </Head>
      <IngressantesTemplate />
    </>
  );
};

export default Ingressantes;
