import React from "react";
import IngressantesForm from "../concepts/ingressantes/componentes/templates/IngressantesForm";
import Head from "next/head";

const Ingressantes: React.FC = () => {
  return (
    <>
      <Head>
        <title>Desafio Muralis - Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/arvore.png" />
      </Head>
      <IngressantesForm />
    </>
  );
};

export default Ingressantes;
